# Generated by Django 3.1.5 on 2021-04-06 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_mess', '0016_auto_20200705_1726'),
        ('central_mess', '0017_auto_20200703_1804'),
    ]

    operations = [
    ]
